#!/usr/bin/env bash
# TypeFlow onboarding — install deps, write dev env files, start backend (Docker).
#
# Usage:
#   ./scripts/onboard.sh                 # full setup; prompts dev vs production Docker
#   ./scripts/onboard.sh --setup-only    # deps + env files, don't start anything
#   ./scripts/onboard.sh --skip-docker   # setup only; use local uvicorn with --reload
#   ./scripts/onboard.sh --dev-docker    # Docker with hot reload (skip prompt)
#   ./scripts/onboard.sh --prod-docker   # Docker, 2 workers, no reload (skip prompt)
#
# After onboarding, run the frontend:
#   npm run dev

set -euo pipefail

# JSON array of localhost origins for dev (frontend auto-picks from :3000)
localhost_cors_json() {
  local start="${1:-3000}" end="${2:-3019}" origins=() p
  for ((p = start; p <= end; p++)); do
    origins+=("\"http://localhost:$p\"")
  done
  local IFS=,
  echo "[${origins[*]}]"
}

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BACKEND="$ROOT/backend"
API_PORT="${API_PORT:-8080}"
FRONTEND_PORT_START="${FRONTEND_PORT_START:-3000}"
CORS_ORIGINS="$(localhost_cors_json "$FRONTEND_PORT_START" $((FRONTEND_PORT_START + 19)))"
SETUP_ONLY=false
SKIP_DOCKER=false
DOCKER_MODE=""  # dev | prod — set by prompt or flags
COMPOSE_FILES=(-f docker/docker-compose.yml -f docker/docker-compose.dev.yml)
DOCKER_DOWN_CMD="docker compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml --env-file .env.docker down"

apply_docker_mode() {
  case "$DOCKER_MODE" in
    dev)
      COMPOSE_FILES=(-f docker/docker-compose.yml -f docker/docker-compose.dev.yml)
      DOCKER_DOWN_CMD="docker compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml --env-file .env.docker down"
      ;;
    prod)
      COMPOSE_FILES=(-f docker/docker-compose.yml)
      DOCKER_DOWN_CMD="docker compose -f docker/docker-compose.yml --env-file .env.docker down"
      ;;
    *)
      die "Internal error: unknown DOCKER_MODE=$DOCKER_MODE"
      ;;
  esac
}

prompt_docker_mode() {
  if [[ -n "$DOCKER_MODE" ]]; then
    return
  fi
  if [[ ! -t 0 ]]; then
    info "Non-interactive shell — defaulting to Docker development mode (hot reload)"
    DOCKER_MODE=dev
    return
  fi

  echo ""
  echo "How should the backend run in Docker?"
  echo "  1) Development — hot reload when you edit backend/app/ (recommended)"
  echo "  2) Production  — 2 workers, no reload"
  echo ""

  local choice
  while true; do
    read -r -p "Choice [1]: " choice
    choice="${choice:-1}"
    case "$choice" in
      1|dev|Dev|development|Development)
        DOCKER_MODE=dev
        break
        ;;
      2|prod|Prod|production|Production)
        DOCKER_MODE=prod
        break
        ;;
      *)
        warn "Please enter 1 (development) or 2 (production)"
        ;;
    esac
  done
}

for arg in "$@"; do
  case "$arg" in
    --setup-only) SETUP_ONLY=true ;;
    --skip-docker) SKIP_DOCKER=true ;;
    --dev-docker) DOCKER_MODE=dev ;;
    --prod-docker) DOCKER_MODE=prod ;;
    -h|--help)
      sed -n '2,11p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $arg (try --help)" >&2
      exit 1
      ;;
  esac
done

info() { printf '\033[1;34m→\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

ensure_uv() {
  if command -v uv >/dev/null 2>&1; then
    return
  fi
  info "Installing uv…"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="${HOME}/.local/bin:${PATH:-}"
  command -v uv >/dev/null 2>&1 || die "uv install failed — see https://docs.astral.sh/uv/"
  ok "uv installed"
}

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '\n'
  else
    python3 -c "import secrets; print(secrets.token_urlsafe(32), end='')"
  fi
}

write_if_missing() {
  local dest="$1"
  local content="$2"
  if [[ -f "$dest" ]]; then
    warn "Already exists, skipping: $dest"
  else
    printf '%s\n' "$content" >"$dest"
    ok "Created $dest"
  fi
}

info "TypeFlow onboarding (API port $API_PORT)"
cd "$ROOT"

# --- prerequisites ---
need_cmd node
need_cmd npm
ensure_uv

if [[ "$SKIP_DOCKER" == false ]]; then
  need_cmd docker
  docker compose version >/dev/null 2>&1 || die "docker compose plugin not found"
fi

# --- frontend ---
info "Installing frontend dependencies…"
if [[ ! -d node_modules ]]; then
  npm install
  ok "npm install"
else
  ok "node_modules present (run 'npm install' yourself to update)"
fi

JWT_SECRET="$(gen_secret)"

# Frontend env (Next.js reads .env.local from its own directory)
FRONTEND_ENV_LOCAL="$ROOT/frontend/.env.local"
write_if_missing "$FRONTEND_ENV_LOCAL" "# Generated by scripts/onboard.sh
NEXT_PUBLIC_TYPEFLOW_API_URL=http://localhost:${API_PORT}"

# --- backend (uv sync for tests / local uvicorn) ---
info "Syncing backend Python deps (uv)…"
(cd "$BACKEND" && uv sync)
ok "Backend Python deps installed (uv.lock)"

# Dev env at project root — read by pydantic-settings when running uvicorn from backend/
ROOT_ENV="$ROOT/.env"
if [[ ! -f "$ROOT_ENV" ]]; then
  cat >"$ROOT_ENV" <<EOF
# Generated by scripts/onboard.sh — used for local uvicorn / alembic (not Docker)
TYPEFLOW_DATABASE_URL=sqlite+aiosqlite:///$BACKEND/typeflow.db
TYPEFLOW_JWT_SECRET=${JWT_SECRET}
TYPEFLOW_CORS_ORIGINS=${CORS_ORIGINS}
TYPEFLOW_COOKIE_SECURE=false
TYPEFLOW_RATE_LIMIT_ENABLED=true
EOF
  ok "Created .env"
else
  warn "Already exists, skipping: .env"
  # Reuse JWT so Docker and local dev stay in sync
  if grep -q '^TYPEFLOW_JWT_SECRET=' "$ROOT_ENV"; then
    JWT_SECRET="$(grep '^TYPEFLOW_JWT_SECRET=' "$ROOT_ENV" | cut -d= -f2-)"
  fi
fi

# Docker Compose reads this file for \${VAR} substitution (must match existing pg volume password)
DOCKER_ENV="$ROOT/.env.docker"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-change-me}"
cat >"$DOCKER_ENV" <<EOF
# Generated by scripts/onboard.sh — used by: docker compose --env-file .env.docker
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
API_PORT=${API_PORT}
WEB_PORT=3000
NEXT_PUBLIC_TYPEFLOW_API_URL=http://localhost:${API_PORT}
TYPEFLOW_JWT_SECRET=${JWT_SECRET}
TYPEFLOW_CORS_ORIGINS=${CORS_ORIGINS}
TYPEFLOW_COOKIE_SECURE=false
EOF
ok "Wrote .env.docker (POSTGRES_PASSWORD=${POSTGRES_PASSWORD})"

# --- docker backend ---
if [[ "$SKIP_DOCKER" == true ]]; then
  warn "Skipped Docker (--skip-docker). Start backend manually:"
  echo "    cd backend && make dev"
elif [[ "$SETUP_ONLY" == true ]]; then
  warn "Skipped Docker (--setup-only). Start with:"
  echo "    cd backend && make docker-dev-d   # development (hot reload)"
  echo "    cd backend && make docker-prod     # production (2 workers)"
else
  prompt_docker_mode
  apply_docker_mode

  if [[ "$DOCKER_MODE" == prod ]]; then
    info "Starting backend via Docker — production (2 workers, no reload)…"
  else
    info "Starting backend via Docker — development (hot reload on backend/app/)…"
  fi

  cd "$ROOT"
  docker compose "${COMPOSE_FILES[@]}" --env-file .env.docker up -d --build

  info "Waiting for API health check…"
  for _ in $(seq 1 30); do
    if curl -sf "http://localhost:${API_PORT}/healthz" >/dev/null 2>&1; then
      ok "API healthy at http://localhost:${API_PORT}/healthz"
      break
    fi
    sleep 1
  done

  if ! curl -sf "http://localhost:${API_PORT}/healthz" >/dev/null 2>&1; then
    die "API did not become healthy — check: docker compose -f docker/docker-compose.yml logs api"
  fi
fi

# --- summary ---
BACKEND_MODE_LINE="not started (use flags or re-run without --setup-only)"
if [[ "$SKIP_DOCKER" == true ]]; then
  BACKEND_MODE_LINE="skipped — run: cd backend && make dev"
elif [[ "$SETUP_ONLY" == false && -n "$DOCKER_MODE" ]]; then
  if [[ "$DOCKER_MODE" == prod ]]; then
    BACKEND_MODE_LINE="Docker production (2 workers, no reload)"
  else
    BACKEND_MODE_LINE="Docker development (hot reload on backend/app/)"
  fi
fi

cat <<EOF

$(printf '\033[1;32mSetup complete.\033[0m')

  Frontend app     : npm run dev  →  http://localhost:${FRONTEND_PORT_START}+ (first free port)
  Backend API      : http://localhost:${API_PORT}  (set in .env.local)
  Backend mode     : ${BACKEND_MODE_LINE}
  Backend health   : curl http://localhost:${API_PORT}/healthz

  Useful commands:
    npm run dev              # start Next.js (hot reload)
    npm run dev:backend      # local uvicorn with --reload (reads .env from project root)
    npm run dev:docker       # restart Docker backend with hot reload
    npm test                 # frontend tests
    cd backend && make test  # backend tests

  Stop Docker backend:
    cd backend && ${DOCKER_DOWN_CMD}

  Reset Postgres (only if you changed POSTGRES_PASSWORD):
    cd backend && ${DOCKER_DOWN_CMD} -v

EOF
